package ssd.uz.wikiquickyapp.entity.enums;

public enum OrderStatus {
    BUYRUTMA_OLINDI, //TAKSICHIO OLDI
    BUYRUTMA_BERILDI, //ZAKAZCHIK BERDI
    BUYRUTMA_YETKAZILDI, //TAKSICHI YETKAZDI
    BUYRUTMA_QABULQILINDI, // CLIENT QABUL QILDI
    BUYURTMA_BEKORQILINDI //
}
